### ISSUE TITLE
Full width source_example containers

### ISSUE THREAD

**Issue by custa1200** [sourcejs/Source#163]
I made a site wide navigation bar and I feel it is limited in being shown in a spec because source_example is set to be inline-block with a fixed width rather than just being block and fullwidth. It makes more sense to me to make it block, I can't see any valid reason or advantage for it to be inline-block.

**Comment by mik01aj** [comment]
When it's inline-block, it can grow bigger to fit the content (note that `.source_example` doesn't have set `width`, only `min-width`).

**Comment by operatino** [comment]
Hi,

It's hard to define one common width logic for `source_example` block for all the enormous use cases. `inline-block` allow to show both small elements and wide elements in acceptable UI.

You can always override `source_example` styles in `user/assets/css/defaults.css` or directly for the spec page. 

There's also a set of modifiers available to use:

```css
.source_example__2 { width: 215px; }
.source_example__3 { width: 730px; }
.source_example__4 { width: 980px; }
.source_example__5 { width: 1200px; }
```
