### ISSUE TITLE
SourceJS CSS is interfering with my Specs.

### ISSUE THREAD

**Issue by custa1200** [sourcejs/Source#214]
The following code in the forms.less file of SourceJS is conflicting with my specs. :(
``` css
// Special styles for iOS temporal inputs
//
// In Mobile Safari, setting `display: block` on temporal inputs causes the
// text within the input to become vertically misaligned. As a workaround, we
// set a pixel line-height that matches the given height of the input, but only
// for Safari. See https://bugs.webkit.org/show_bug.cgi?id=139848

@media screen and (-webkit-min-device-pixel-ratio: 0) {
  input[type="date"],
  input[type="time"],
  input[type="datetime-local"],
  input[type="month"] {
    line-height: @input-height-base;
    ...
  }
}
```

**Comment by ndelangen** [comment]
I suggest we add a `.source_inputelement` on all `<input ... />`s and style it like this:

```css
@media screen and (-webkit-min-device-pixel-ratio: 0) {
  .source_inputelement[type="date"],
  .source_inputelement[type="time"],
  .source_inputelement[type="datetime-local"],
  .source_inputelement[type="month"] {
    line-height: @input-height-base;
    ...
  }
}
```

**Comment by custa1200** [comment]
I would suggest namespacing everything using "sourcejs-*" and using BEM, so it would be something like :
```css
@media screen and (-webkit-min-device-pixel-ratio: 0) {
  .sourcejs-input[type="date"],
  .sourcejs-input[type="time"],
  .sourcejs-input[type="date-time-local"],
  .sourcejs-input[type="month"] {
    line-height: @input-height-base;
    ...
  }
}
```
the element seems a bit redundant, everything is an element. Could even BEM it further by making them 

```css
@media screen and (-webkit-min-device-pixel-ratio: 0) {
  .sourcejs-input--date,
  .sourcejs-input--time,
  .sourcejs-input--date-time-local,
  .sourcejs-input--month {
    line-height: @input-height-base;
    ...
  }
}
